<h1>데이터 전처리를 위한 인코딩</h1>

컬럼 중 문자형/범주형인 데이터를 숫자로 변환하는 작업        
컴퓨터가 분석 및 학습을 하기 쉽도록 변환  

정수 인코딩/ 정수라벨링  
원-핫 인코딩

In [31]:
import pandas as pd
import numpy as np
import sys
sys.path.append(R'C:\Users\KDT38\Desktop\KDT_14\[2]PANDAS\utils')
import utils as u

In [32]:
#  데이터 준비 및 DF 인스턴스 생성
DATA_FILE = '../DATA/iris.csv'

# 컬럼 인덱스 있음. 구분자는 콤마임.
iris_df = pd.read_csv(DATA_FILE)

In [33]:
# DF 인스턴스 확인
u.data_info(iris_df)

--------------------------------------------------------------
0. 요약 정보 반환
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
--------------------------------------------------------------

--------------------------------------------------------------
1. 실제 데이터 확인하기
    sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

--------------------------------------------------------------

--------------------------------------------------------------
2. 실제 데이터 확인하기
   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
--------------------------------------------------------------

--------------------------------------------------------------
3. 실제 데이터 확인하기

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
     sepal.length  sepal.width  petal.length  petal.width    variety
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica
--------------------------------------------------------------

--------------------------------------------------------------
4. 수치 컬럼별 정보

       sepal.length  sepal.width  petal.length  petal.width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000
--------------------------------------------------------------

--------------------------------------------------------------
5. 모든 컬럼별 정보

        sepal.length  sepal.width  petal.length  petal.width variety
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  Setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN
--------------------------------------------------------------

In [34]:
iris_df.head(2)

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa

variety 컬럼 object >>> 숫자/정수 라벨 인코딩

In [47]:
# 품종명에 설정될 값 매핑
irisDF_map = {
"Setosa": 0,
"Versicolor": 1,
"Virginica": 2
}

## 결측값 NaN에는 함수 적용하여 NaN. 결과를 새로운 컬럼으로 추가
iris_df["variety_label"] = iris_df['variety'].map(irisDF_map)
## 결측값 NaN에는 함수를 적용하지 않음
iris_df["variety_label"] = iris_df['variety'].map(irisDF_map, na_action='ignore')

In [53]:
iris_df.head(3)

   sepal.length  sepal.width  petal.length  petal.width variety  variety_label
0           5.1          3.5           1.4          0.2  Setosa              0
1           4.9          3.0           1.4          0.2  Setosa              0
2           4.7          3.2           1.3          0.2  Setosa              0

In [54]:
iris_df.tail(3)

,sepal.length,sepal.width,petal.length,petal.width,variety,variety_label
147,6.5,3.0,5.2,2.0,Virginica,2
148,6.2,3.4,5.4,2.3,Virginica,2
149,5.9,3.0,5.1,1.8,Virginica,2

특정 값만 1로 설정하는 인코딩: 원-핫 인코딩

In [60]:
iris_df2 = pd.get_dummies(iris_df, columns=["variety"], dtype=int)

In [63]:
iris_df2.tail(10)

,sepal.length,sepal.width,petal.length,petal.width,variety_label,variety_Setosa,variety_Versicolor,variety_Virginica
140,6.7,3.1,5.6,2.4,2,0,0,1
141,6.9,3.1,5.1,2.3,2,0,0,1
142,5.8,2.7,5.1,1.9,2,0,0,1
143,6.8,3.2,5.9,2.3,2,0,0,1
144,6.7,3.3,5.7,2.5,2,0,0,1
145,6.7,3.0,5.2,2.3,2,0,0,1
146,6.3,2.5,5.0,1.9,2,0,0,1
147,6.5,3.0,5.2,2.0,2,0,0,1
148,6.2,3.4,5.4,2.3,2,0,0,1
149,5.9,3.0,5.1,1.8,2,0,0,1